### ISSUE TITLE
Terseness

### ISSUE THREAD

**Issue by lascellesabercrombie** [fac24/week5-Joe-Maria#28]
https://github.com/fac24/week5-Joe-Maria/blob/1c5e3d281b968660f57687285df165c332ce5c04/week5-joe-maria/src/ShowQuiz.jsx#L4

I think

`const { gameState, setGameState, category, quizLength } = props;`

should work(?)

**Comment by mariaalouisaa** [comment]
Thanks for the tip. This has just been implemented 🙂
